### ISSUE TITLE
How can I stop periodic task?

### ISSUE THREAD

**Issue by chapkovski** [arteria/django-background-tasks#100]
I can start periodic task by running
`myfun(repeat=60)`
but what is the right way to stop it?

**Comment by walterrenner** [comment]
Hi @chapkovski 
Periodic tasks can best stopped by deleted them from the Database.

**Comment by walterrenner** [comment]
As i can see you managed to resolve #98.
Please consider closing Issues as they are resolved or give feedback so we can close them. 👍

**Comment by enterpredator** [comment]
How can we stop it inside task itself?
For now if you try to remove Task from database - the task will have time to be recreated with the new id

**Comment by JaimeSilva** [comment]
I have the same question

**Comment by ahmadore** [comment]
@enterpredator You might need to stop the process that is running this, `python manage.py process_tasks`. Then delete the task from the database, and restart the process ones again

**Comment by soekarmana** [comment]
for anyone who still got problem with this
to stop periodic task from running, just delete it from database with :

```python
Task.objects.get(task_hash=the_task_hash).delete()
```

poof, gone!
why using task_hash? : because id changed every time it repeats, but task_has does not
