### ISSUE TITLE
Pypi package is un-installable

### ISSUE THREAD

**Issue by kofic** [arteria/django-background-tasks#101]
Hello - I installed the package from pypi (https://pypi.python.org/pypi/django-background-tasks) - but I could not get it running because the application fails with a migration error. 

```
django.db.migrations.exceptions.NodeNotFoundError: Migration background_task.0001_initial dependencies reference nonexistent parent node (u'contenttypes', u'0002_remove_content_type_name')
```
It looks like the py package was shipped with a migration file. It may have worked on your development machine because the dependent file was available on your system. FYI - its best practice to ship packages without the migration files and allow the 0001_initial migration to be created on the installer's machine by running makemigrations. So - basically before you ship the package - delete all the files in the migration folder except the ```__init__.py``` file and that should work.

**Comment by walterrenner** [comment]
Hi @kofic

The `(u'contenttypes', u'0002_remove_content_type_name')` is django.contrib.contenttypes migrations file.
If you use one of the supported versions of Django, which are 1.8, 1.9, 1.10 and 1.11¹ migrations should work.

I disagree with your opinion on migrations. Most reusable apps with models are shipped with migrations. However, you can use your own migrations for specific apps by providing `MIGRATION_MODULES`² in your settings.py file.

If you still have problems installing django-background-tasks please don't hesitate to ask.

¹ https://github.com/arteria/django-background-tasks/blob/master/tox.ini#L3
² https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-MIGRATION_MODULES

**Comment by kofic** [comment]
Thanks for the suggestions Walter - I ended up forking the code.
Thanks to you and community for such a great product.

On the migration file philosophy - I respect your opinion but not
every project is in the state that will have
'0002_remove_content_type_name.py' file. For instance my current
projects have squashed migration files so that particular migration
file is not available. Anyways - like I said I fixed it by forking the
code so no biggie. Thanks for taking the time.

**Comment by walterrenner** [comment]
Sorry to hear that you have to maintain your own fork, but we created the migrations file by following the documentation and best practices.

We also run `makemigrations` with the lowest Django version that is supported (which is Django 1.8 at this time).
Relevant documentation: https://docs.djangoproject.com/en/1.11/topics/migrations/#supporting-multiple-django-versions.

I will close this Issue and your PR since you found a fix which works for your.
