### ISSUE TITLE
[Feature] - Way to set maximum task concurrency

### ISSUE THREAD

**Issue by cory-weiner** [arteria/django-background-tasks#105]
It would be great to have a way to set a maximum concurrency limit by task. 

For example, if I create 100 tasks to be executed asynchronously starting now, it would be great if I could set them to have no more than 10 executing concurrently, with the subsequent tasks beginning execution as the former tasks complete.

**Comment by walterrenner** [comment]
Please take a look at the BACKGROUND_TASK_RUN_ASYNC and BACKGROUND_TASK_ASYNC_THREADS settings.

http://django-background-tasks.readthedocs.io/en/latest/#settings
