### ISSUE TITLE
Process_tasks doesn't do anything

### ISSUE THREAD

**Issue by cory-weiner** [arteria/django-background-tasks#106]
I'm trying to run a very simple task,

Inside of my app (the same folder that has views, urls, settings) I have a very simple tasks.py:

**obieeadmin>tasks.py**
```
from background_task import background

@background(schedule=1)
def process_batch():
	print 'Success'
```

I open the shell and add a task:
```
>>> from obieeadmin.tasks import *
>>> process_batch()
<Task: obieeadmin.tasks.process_batch>
```

I start up the process_tasks server:

`python manage.py process_tasks`

And that is where I'm stuck. The process tasks command doesn't print anything out or appear to be doing anything. I look inside of the admin panel and I can see all of the tasks I've added, but they all have 0 attempts at running, no errors. etc.

Attached is a screenshot of the task that was created
![2017-07-06-10-03-127 0 0 1-8000](https://user-images.githubusercontent.com/137638/27917690-5cfc3ce2-6232-11e7-9c92-cec27fb1fdd9.png)

**Comment by walterrenner** [comment]
Hi @cory-weiner can you please give feedback what was wrong. This may help other users too. Thanks

**Comment by cory-weiner** [comment]
Yes, the issue was my tasks.py was located inside of my project folder. It looks like it has to be located inside one of the installed apps. I moved from the project folder to the app folder and it started working.
