### ISSUE TITLE
Managing multiply queues or reschedule task

### ISSUE THREAD

**Issue by bigretromike** [arteria/django-background-tasks#108]
Hey,

Been using this project some time now. But Im having hard time figuring out one thing.
Let me give you use case:
Im quering server that expsosed that thru api, I use 3 commands (one for status, one for jobs on that server, one for listing log) and I use 3  queues (named: general, jobs, logs). Commands that have limits from server side are in jobs queue. I would like to stop `jobs` queue when ever API limit is hit as it can take few to many minutes when limit is reset. 

Can I somehow do that from inside django? Or which Error should I raise and how to handle it to be able to post-pone command for later (as I read from doc that it will reschedule for later on error - but which one? raise Exception would be enought? )

**Comment by singhabhinav** [comment]
Hi @bigretromike 

Did you find any solution to that?

**Comment by bigretromike** [comment]
Yes, but i mamaged it outside tasks i just add mutex that would put task in sleep if limit is jit and as it sleep it clog list of jobs so it almost what i wanted but not inside background tasks
