### ISSUE TITLE
Django migrations remove model CompletedTask

### ISSUE THREAD

**Issue by alexdashkov** [arteria/django-background-tasks#112]
When I run migrations I got the output:

- Remove field creator_content_type from completedtask
- Delete model CompletedTask

and migration:

```
class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='creator_content_type',
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
```
and all gone good but when I run tasks django raise an error django.db.utils.OperationalError: no such table: background_task_completedtask

Why django remove this table and how can I avoid it? Should I just ignore this migration or there is some more clever way?

P.S. I already check simial questions but I didn't find the solution.

I can fake this migration but got another problem. django-background-tasks register each task two times (I call only one time). Could you suggest how to cook it?

**Comment by walterrenner** [comment]
Someone else is running into this Error? I cannot reproduce.

**Comment by alexdashkov** [comment]
@walterrenner I run it using Django 1.11 and python 3.5. Maybe it can help to reproduce the error.

**Comment by grote** [comment]
I run Django 1.11 and python 3.5 as well, but can not reproduce this. Maybe provide a minimal example and steps to reproduce?

**Comment by walterrenner** [comment]
@alexdashkov you managed to fix this?

**Comment by joncard1** [comment]
I am having this problem, and do not know what to do about this; whether to create a new issue or not. I am running Django 2.0.3 on Python 3.6.4. When I run makemigrations on a fresh install of django-background-tasks (1.1.13) in my environment, it produces the following output:

$ python manage.py makemigrations --settings=nbserver.settings.dev
Migrations for 'background_task':
  /home/JonathanCard/nbserver/lib/python3.6/site-packages/background_task/migrations/0003_auto_20180328_0451.py
    - Remove field creator_content_type from completedtask
    - Delete model CompletedTask

I believe the reason is that makemigrations is looking in models.py for the models, and not including models_completed.py.

**Comment by mctinetti** [comment]
I also have this issue.
Running django 1.11.12 and django-background-tasks (1.1.13), using a virtualenv-
For the moment I'm just removing this from the migration file: 0003_auto_20180417_1203.py
`
# migrations.DeleteModel(
 #           name='CompletedTask',
 #       ),
`

**Comment by winged** [comment]
I had the same problem on Django 2.1. Seems like it doesn't correctly detect the model in `background_task.models_completed`. Will send a PR once I'm sure it looks good (basically it moves the model and queryset classes from `background_task.models_completed` to `background_task.models`)

**Comment by jtimmons** [comment]
Ran into this issue with Django 2.1 and django-background-tasks 1.2.1 while looking into another issue. Can reproduce it from a fresh clone by running:

```
$ python3.6 -m venv venv
$ source ./venv/bin/activate
$ pip install -r requirements.txt -r requirements-test.txt django==2.1
$ python manage.py makemigrations
```

@walterrenner can you reopen this issue? This is especially a problem when attempting to make changes to either the `Task` or `CompletedTask` model that require database migrations.

**Comment by michaelbukachi** [comment]
Is there any solution for this?

**Comment by michaelbukachi** [comment]
I was able to discover the issue. It seems putting `CompletedTask` in `models_completed.py` makes it invincible to django. [This](https://www.webforefront.com/django/modelsoutsidemodels.html) article elaborates further. A [pull request](https://github.com/arteria/django-background-tasks/pull/170) has already been made with the fix.
