### ISSUE TITLE
Task code isn't reloaded every time a task is executed

### ISSUE THREAD

**Issue by bsquidwrd** [arteria/django-background-tasks#114]
I may be talking about this wrong, but when I run a task, update the code then run the task again, my updated task code isn't being run. Is there a setting somewhere I need to set or is this maybe expected behavior?

Edit: The only time the new code is run is if I restart the `process_tasks` management command, but if I leave it running as a systemd service then changing the code doesn't run until restart of the service.

Example code of how I'm doing everything:

## tasks.py
```python
from background_task import background


@background()
def process_task(hello, world):
    try:
        print("{0}, {1}!".format(hello, world))
    except Exception as e:
        print(e)
```

## views.py
```python
from . import tasks


def my_view(request):
    ...
    tasks.process_task(hello="Hello", world="World")
    ...
```

If I swap the task code to be the following, then rerun the view I am would still be running the code above:

## tasks.py (edited)
```python
from background_task import background


@background()
def process_task(hello, world):
    try:
        print("{0}, {1}!".format(world, hello))
    except Exception as e:
        print(e)
```

**Comment by walterrenner** [comment]
@bsquidwrd this is expected behavior. You have to restart `process_tasks` command on every code change. Just like you would do with your Django project.

**Comment by bsquidwrd** [comment]
@walterrenner The problem with that though is that if there is a process running, I will have to clear out all pending tasks and hope they get started again. Otherwise, the tasks just sit there as being locked by a PID but not actually finishing (in my experience)

**Comment by walterrenner** [comment]
You can send a SIGTSTP Signal to your process_tasks command. If the command receives this signal no more tasks will be qeued and the command will be stopped after all pending tasks are processed.

Then you can restart process_tasks command and no tasks are locked by a dead pid.

This feature is no fully tested and therefore not documented so you are very welcome to try and experiment.

[relevant code](https://github.com/arteria/django-background-tasks/blob/31b9202906d7af2cab58a5fb963a7cd59da8742a/background_task/utils.py)

**Comment by bsquidwrd** [comment]
Hmmm, so with my small amount of testing, I can't seem to get the expected behavior on Ubuntu 16.04 LTS.

I've tried sending the kill code SIGTSTP from terminal and python with no luck to get it to finish the currently processing tasks.

**Comment by unformatt** [comment]
This seems to work on Ubuntu 18.04.2

`pkill -20 -f process_tasks`

**Comment by unformatt** [comment]
Following up because it seems like `pkill -SIGTSTP -f process_tasks` doesn't gracefully kill the `process_tasks` command afterall. Seems like it instantly kills the task (which is a child thread of the `process_tasks` command?) and _then_ the command "gracefully" exits.
