### ISSUE TITLE
Task repetition created in the past

### ISSUE THREAD

**Issue by grote** [arteria/django-background-tasks#115]
The [idea of task repetitions](http://django-background-tasks.readthedocs.io/en/latest/index.html#repeating-tasks) is to repeat a task each `n` seconds. This is fine for use-cases where task processing is always running.

When task processing is not always running, this can create a problem. For example, imagine a daily task and the processing stopping for one week. When the processing resumes, the same task will be run `7` times in short succession.

Is this the intended behavior?

Could you imagine changing this, so that [Task.create_repetition()](https://github.com/arteria/django-background-tasks/blob/811bc7015c8c699ace5147b30a7671d85904ffe3/background_task/models.py#L278) only creates repetitions in the present and future, but not in the past?

**Comment by walterrenner** [comment]
We didn't ran into this problem before so i cannot say this is intended or not. But our task processing is always running so this is not a problem we we intend to solve now.

Basically this is not big problem. I think this can be solved very easy by

* creating a new tasks `n` seconds from `Task.run_at` (like this is the case now) 

or

* creating a new tasks `n` seconds from `timezone.now()`.

[relevant lines of code](https://github.com/arteria/django-background-tasks/blob/811bc7015c8c699ace5147b30a7671d85904ffe3/background_task/models.py#L290)

The second case has one downside. You cannot keep up a period if required. So if you started you first Task at 00:00 and the tasks took 5 seconds, your next run_at time will be 5 seconds delayed.

This can either be solved per Tasks or per application. For a per Task solution we need another property for the Task model, for application level we need to introduce a new Setting that can be set.

If you would like to implement this changes you always can provide a Pull Request.

**Comment by grote** [comment]
I'd be happy to provide a pull request once we agree what it should do.

> The second case has one downside. You cannot keep up a period if required.

I guess it would be best to keep the current behavior of sticking to the fixed period to not break existing users of this library.

Couldn't we simply do something like this (pseudo-code):
```python
new_run_at = self.run_at + timedelta(seconds=self.repeat)
while new_run_at < timezone.now():
    new_run_at = new_run_at + timedelta(seconds=self.repeat)
```

For most users, the condition should always be false, so not even enter the loop. For my use-case, it would just schedule the next repetition in the future and even keep the period.

**Comment by bigretromike** [comment]
default behavior is that it will trigger after restarting process. 
I can confirm this.

**Comment by bigretromike** [comment]
@walterrenner `Task.run_at` wouldn't resolve this as the task need to repeat I assume you would need schedule new process at end of old one. That would be not the case when application would shutdown, on new start it would just not spam with older task. 

The application would have to handle creating new task at start. 

That or what ?

**Comment by domdinenno** [comment]
You basically just need a refresh state to be run before the function call  "process_tasks".  

Example :
`from background_task.models import Task
Task.objects.all()delete()
`
Could overwrite Django-background-tasks module and add it in before a function call or create a custom management command which runs this and shortly after '... manage.py process_tasks'

**Comment by grote** [comment]
@walterrenner could you please confirm whether https://github.com/arteria/django-background-tasks/issues/115#issuecomment-332563737 would be a valid solution you would accept a PR for?

**Comment by walterrenner** [comment]
@grote the solution you provided is fine. Waiting for your PR.

**Comment by walterrenner** [comment]
@grote your changes are available in the lastest version. thanks for your PR
