### ISSUE TITLE
Tasks can't call other function

### ISSUE THREAD

**Issue by mic-rigaud** [arteria/django-background-tasks#117]
Hello,

I have a problem, I can't call other function in my tasks. 

For example, the code beside doesn't work:

```
@background(schedule=60)
def test_hello():
    hello()

def hello():
    logger.debug('hello')
```

Is there a problem with my code? Or is it a limitation of the pluggin (I didn't see anything in the documentation about it)? 

Thank you so much,

**Comment by arthurbarros** [comment]
The issue is that your function `hello()` is not yet defined for the `test_hello()` yet, move your function up like this and everything will be fine

```
def hello():
    logger.debug('hello')

@background(schedule=60)
def test_hello():
    hello()
```
