### ISSUE TITLE
how to prevent task process exiting 

### ISSUE THREAD

**Issue by cqbupter** [arteria/django-background-tasks#119]
HELLO!
   My tasks are revlant with mysql databases, but background task process would exit when  there are mysql exceptions,  so how to  prevent process exiting except catching all exceptions, thanks a lot!

**Comment by walterrenner** [comment]
Django has a lot of exceptions that you can use.
See https://docs.djangoproject.com/en/1.11/ref/exceptions/#database-exceptions

**Comment by philippeowagner** [comment]
Could we close this?
