### ISSUE TITLE
How to drop certain tasks?

### ISSUE THREAD

**Issue by doctor-yes** [arteria/django-background-tasks#123]
How to drop certain tasks or clear the task queue? During development, there could be multiple tasks which will not return due to error etc. Looks like those tasks are retired. How can I stop that? Thanks.

**Comment by walterrenner** [comment]
You can set settings.MAX_ATTEMPTS to 1.

Please consider the documentation for more information http://django-background-tasks.readthedocs.io/en/latest/#settings
