### ISSUE TITLE
How do I make task unique

### ISSUE THREAD

**Issue by alivenets** [arteria/django-background-tasks#127]
I want to make my tasks unique in the queue.
In python script I write:
`
long_task(repeat=Task.DAILY, schedule=timezone.now())
`
On every execution, new record is added to the table. How can I avoid this? Is there are property parameter to make task unique?

**Comment by walterrenner** [comment]
Hi @alivenets 

each Task has a sha1 hash which is calculated when the Task is created. Here you can see how it's done:

https://github.com/arteria/django-background-tasks/blob/master/background_task/models.py#L109-L110

when you calculate the hash in your python code before creating a new Task. You could check if such Task already exists.

**Comment by alivenets** [comment]
Hi @walterrenner 

Actually, i've found the solution myself:
`
long_task(repeat=models.Task.DAILY, schedule={'run_at': timezone.now(), 'action': tasks.TaskSchedule.RESCHEDULE_EXISTING})
`
