### ISSUE TITLE
Unable to process a task (send mail)

### ISSUE THREAD

**Issue by limtaesu** [arteria/django-background-tasks#13]
WARNING:root:Rescheduling Task(account.views.send_code)
    Traceback (most recent call last):
      File "/home/t/env/local/lib/python2.7/site-packages/background_task/tasks.py", line 172, in run_task
        tasks.run_task(task.task_name, args, kwargs)
      File "/home/t/env/local/lib/python2.7/site-packages/background_task/tasks.py", line 54, in run_task
        task = self._tasks[task_name]
    **KeyError: u'account.views.send_code'**
    WARNING:root:Rescheduling task Task(account.views.send_code) for 0:00:06 later at 2015-05-16 18:54:01.832337+00:00

`account/view.py` contains:

    @background(schedule=10)
    def send_code(email, code):
        send_mail(
            "It works!", "This will get sent through Mandrill<ahref=http://127.0.0.1:8000/confirm/"+code+">confirm</a>",
            "Djrill Sender <djrill@example.com>", [email]
            )

Works fine w/o backgroun-tasks.
I am looking through the code to see where the problem lays.

**Comment by limtaesu** [comment]
`tasks._tasks` dict is empty for some reason.

**Comment by philippeowagner** [comment]
To make this work, please note (from README.rst): 

> NB: to aid the management task in finding the registered tasks it is best to put them in a file called 'tasks.py'. You can put them elsewhere, but you have to ensure that they will be imported so the decorator can register them with the scheduler. By putting them in tasks.py they will be auto-discovered and the file automatically imported by the management command.
