### ISSUE TITLE
It can't start the jobs

### ISSUE THREAD

**Issue by easyzs** [arteria/django-background-tasks#134]
I installed the django-background-tasks for my project
Environment: windows, mssql, Django 1.8

I can register a task and it stored in DB
but
When I try to run that (python manage.py process_tasks), nothing happend. The Database doesn't changed and the tasks doesnt't ran.

When I see the logs:
#
#
DEBUG 2018-04-25 14:57:18,627 process_tasks 4492 10936 waiting for tasks
#
DEBUG 2018-04-25 14:58:59,565 utils 4492 10936 (0.002) QUERY = u'SAVE TRANSACTION [s10936_x21]' - PARAMS = (); args=None
DEBUG 2018-04-25 14:58:59,588 utils 4492 10936 (0.019) QUERY = u'SELECT [background_task].[id], [background_task].[task_name], [background_task].[task_params], [background_task].[task_hash], [background_task].[verbose_name], [background_task].[priority], [background_task].[run_at], [background_task].[repeat], [background_task].[repeat_until], [background_task].[queue], [background_task].[attempts], [background_task].[failed_at], [background_task].[last_error], [background_task].[locked_by], [background_task].[locked_at], [background_task].[creator_content_type_id], [background_task].[creator_object_id] FROM [background_task] WHERE (([background_task].[locked_by] IS NULL OR [background_task].[locked_at] < %s) AND [background_task].[failed_at] IS NULL AND [background_task].[run_at] <= %s) ORDER BY [background_task].[priority] DESC, [background_task].[run_at] ASC' - PARAMS = (u'2018-04-25T13:58:59.567000', u'2018-04-25T14:58:59.567000'); args=('2018-04-25T13:58:59.567000', '2018-04-25T14:58:59.567000')
#
#
Could somebody help me?

**Comment by davidzwa** [comment]
Same for me here. Django 2.0.4

I can run the example project fine tho

**Comment by easyzs** [comment]
Thanks for your help!
I upgraded django to 1.11 and python 3.6 after that it is works correctly.
My db connector has a problem with datetimeoffset type. I resolved it too.
