### ISSUE TITLE
Task scheduler not tolerant to database outages

### ISSUE THREAD

**Issue by jtimmons** [arteria/django-background-tasks#138]
The task scheduler run via the `process_tasks` management command crashes and exits when it's not able to connect to a database when trying to pull the next task to run. This tends to be a problem when running for long periods of time and using a database which does not have 100% uptime. I would expect that the task scheduler be tolerant to these outages, log an error and attempt to reconnect at a later time.

Steps to reproduce:
1. Create new local database, configure django to point to it
2. Start process_tasks
3. Interrupt running database service

I would be happy to contribute a fix for this with some guidance from one of the maintainers. At the moment (and with my very limited look into the codebase), it seems like the lowest lift solution would be to catch database errors in `DBTaskRunner::get_task_to_run`, log an error an try again at the next check time. It could also be sensible to include an exponential backoff for database failures similar to how individual task failures are handled, but I'm not where that should live at the moment.

Attached traceback: [traceback.txt](https://github.com/arteria/django-background-tasks/files/1989418/traceback.txt)

**Comment by davidzwa** [comment]
So `manage.py process_tasks` is called externally right? Something called that manage command and in case it crashes that same thing can re-start it. My suggestion is to make a Python script (and also cron job on a python script!) to re-run process-tasks every now and then, since you will do this when new code is available. Then you can log the database outage yourself and wait for it to reconnect again and restart the command.

Seems the easiest solution for me.

**Comment by jtimmons** [comment]
Using a supervisor at the level above the task scheduler seems a little heavy-handed for this. Other task schedulers (such as [celery](http://www.celeryproject.org/) or [APScheduler](https://apscheduler.readthedocs.io/en/latest/userguide.html)) are tolerant to task queue outages, so it doesn't seem unreasonable to expect django-background-tasks to be able to handle this as well.

We're running our application through AWS' Elastic Beanstalk w/ RDS for the database. The uptime on our database is fine, but the DNS lookup occasionally fails for the database which seems to be [a](https://forums.aws.amazon.com/thread.jspa?threadID=71595) [persistent](https://forums.aws.amazon.com/thread.jspa?threadID=88381) [issue](https://aws.amazon.com/premiumsupport/knowledge-center/partial-dns-failures/) in AWS' VPCs. We also can't use IP addresses to reference our database because the location is only exposed via the elastic hostname via [Elastic Beanstalk environment variables](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.RDS.html).

**Comment by philippeowagner** [comment]
Thanks @jtimmons  for filing an issue and providing a PR! I will merging after reviewing it.

**Comment by jtimmons** [comment]
We've been using the fix for a couple of months now and it seems to be addressed - closing this out.

**Comment by unformatt** [comment]
For anyone else looking for a solution, I run `process_tasks` in screen in a `while` loop that will restart `process_tasks` if it exits:

`
screen -d -S process_tasks -m bash -c "cd /opt/my-project; while true; do python manage.py process_tasks; echo 'restarting in 2s'; sleep 2; done"
`
