### ISSUE TITLE
IntegrityError and migrate fail

### ISSUE THREAD

**Issue by diogosimao** [arteria/django-background-tasks#139]
I'm running `migrate` after installing `background_task` with `Django==1.11.13`, `django-background-tasks==1.1.13` and it won't finish with success. Previously installed `django-background-task==0.1.8` with `Django==1.5.1`

In fact the first `migrate` might have been ran with an older version of Django and the MySQL database set-up is old and is a production copy.

I get the following error on Django Admin:
    `IntegrityError at /admin/background_task/task/add/`

and after `migrate` I get the following error:

```
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1364, "Field 'name' doesn't have a default value")
```

What kind of information would help if i give in order to get me to find some fix?
Thanks!
Linking [issue](https://github.com/lilspikey/django-background-task/issues/21)

**Comment by davidzwa** [comment]
Remove the migrated tables `background_task` and `background_task_completedtask` manually and remove their migration-rows from `django_migrations`.
Then rerun migrate

Good luck

**Comment by diogosimao** [comment]
I have found no other solution than run:
`mysql> ALTER TABLE django_content_type MODIFY COLUMN name character varying(50) NOT NULL DEFAULT 'not null';`
and moved on.

**Comment by philippeowagner** [comment]
Please reopen if the error persists in 1.2.5+ (1.2.5 will be released soon).

**Comment by maxim-lixakov** [comment]
> I have found no other solution than run: `mysql> ALTER TABLE django_content_type MODIFY COLUMN name character varying(50) NOT NULL DEFAULT 'not null';` and moved on.

It helped me! couldn't find a table where it fails, thank you
