### ISSUE TITLE
Timezone not supported

### ISSUE THREAD

**Issue by davidzwa** [arteria/django-background-tasks#140]
It seems that timezone support is a problem for me.
Times get entered 2 hours before my time (Netherlands +1h, so +2 from UTC)

Tasks arent fired because of it.

**Comment by felocru** [comment]
I have the same problem, when creating a task it registers 5 hours later and consequently they do not shoot either. Could you solve it?

**Comment by philippeowagner** [comment]
@felocru @davidzwa could you please double-check your `settings.py`?

**Comment by felocru** [comment]
Hi, thank you for you answer. I had a problem in the settings. Since I stopped working on the project that used background-tasks, I do not remember what it was.
The background jobs run correctly, but I still have problems with the time zone.

**Comment by philippeowagner** [comment]
Please reopen if required.

**Comment by davidzwa** [comment]
I had timezone correctly setup! 
<pre>
# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Amsterdam'
USE_I18N = True
USE_L10N = True
USE_TZ = True
</pre>

So to my knowledge the runner would be timezone agnostic. Im not on the project anymore, so wouldnt know for sure. I can always run the project again and check if you are sure the bug is not on DBG-tasks' side.
