### ISSUE TITLE
question: will background tasks be affected by exceptions in django views?

### ISSUE THREAD

**Issue by DoubleCouponDay** [arteria/django-background-tasks#143]
I am building a django application with django-background-tasks. It is of high importance that the background tasks remain running if a an unexpected error occurs within the webserver. Assuming that an unexpected error will eventually occur:

-what will happen to the background tasks if an `http 500 internal server error` is thrown? 
-Inversely, what will happen if a background task throws an internal server error? 
-how will an error within the background task propagate into the web server console prints?

Please excuse my lack of testing. I wish to tap the knowledge of the maintainers for this project.

sincerely,
sam

**Comment by philippeowagner** [comment]
`process_tasks` and the web processes (eg. `runserver`) are decoupled. 
It's possible to deploy/restart the web part and keep the tasks running in the background. 
Edge-cases are migrations for example.
