### ISSUE TITLE
Multiple process_tasks running

### ISSUE THREAD

**Issue by elliotjberman** [arteria/django-background-tasks#149]
Using:
 - django 1.11
 - django-background-tasks 1.1.13
 - MySQL db

Trying to run several process_tasks scripts on several machines which all target the same DB. However, each script locks out the other from accessing the table entirely, not just by individual task. Is this a bug or just outside the scope of intended use cases for django-background-tasks?

**Comment by philippeowagner** [comment]
It's out of scope - for the moment at least. Just use one process_tasks per database.
The idea is to have a super simple background task runner with small footprint, easy setup, ..
