### ISSUE TITLE
Not Running After placing file in app directory

### ISSUE THREAD

**Issue by bobozar** [arteria/django-background-tasks#155]
I'm trying this package for the first time. When I run the task manually via django shell, it will work. But when I run it with the command python manage.py process_tasks --settings=projectname.settings_dev, it won't work, nothing gets printed on the terminal

```
@background(schedule=60)
def run_check_repayment():
    check_user = User.objects.filter(username='dddd')
    if check_user.exists():
       #do something.
    else:
        print('can\'t find any buddy')](url)
```

```
>>> from myapp.tasks import *
>>> run_check_repayment()
<Task: myapp.tasks.run_check_repayment>
>>> run_check_repayment()
<Task: myapp.tasks.run_check_repayment>
```

I also set BACKGROUND_TASK_RUN_ASYNC = True .

Python 3.5 and Django 2.0.

What am I missing?

**Comment by Hey-tom** [comment]
Did you get an answer? The documentation for this module is a joke

**Comment by philippeowagner** [comment]
@bobozar The Django shell or the web process calls `run_check_repayment`. The task will be added to the queue and executed by process B (process_tasks) after 60 seconds. 
If it's not executed, maybe  #174 could be the reason that the task is not picked up.

@Hey-tom You are free to use this module, which has been developed, extended and maintained through countless hours of work. You are free to use this module without any costs. 
But you are not entitled to free support here or to get answers to all your questions per se. 

What about contributing and improve the documentation?

**Comment by philippeowagner** [comment]
Closing this now.
