### ISSUE TITLE
Refactor logging mechanism.

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#16]
Use [Django's built in logging system](https://docs.djangoproject.com/en/1.8/topics/logging/) instead of the one [implemented in the management command](https://github.com/arteria/django-background-tasks/blob/master/background_task/management/commands/process_tasks.py#L42).

**Comment by jvamvas** [comment]
@philippeowagner  Implemented in the current master branch:

  * Use logging as recommended in https://docs.djangoproject.com/en/stable/topics/logging/
  * Remove `log-file` and `log-level` options from management command `process_tasks`. The django [`LOGGING`](https://docs.djangoproject.com/en/stable/topics/logging/#configuring-logging) setting can be used instead

**Comment by walterrenner** [comment]
@jvamvas this is resolved in 1.1.0rc2, right?

**Comment by jvamvas** [comment]
@walterrenner Right.
