### ISSUE TITLE
Best way to add cronjob for process_tasks? Concerned about duplicate processes

### ISSUE THREAD

**Issue by phithor** [arteria/django-background-tasks#161]
Hi, i have understood that the default is that the process itself checks the database every 5 seconds. What cron parameters are you guys using in production for ensuring the process tasks is being run?

Thank you very much

**Comment by philippeowagner** [comment]
We use supervisor in combination with this `run`-script.
Basically we activate the virtualenv and keep `python manage.py  process_tasks` up and running. 
```
#!/usr/bin/env bash
cd /var/www/www.example.com/ && . ./bin/activate
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
exec setuidgid www-data python manage.py process_tasks
```
