### ISSUE TITLE
Not possible to store a task result?!?

### ISSUE THREAD

**Issue by jedie** [arteria/django-background-tasks#164]
Is it right that there is no way to save a task return value?

**Comment by philippeowagner** [comment]
This is correct, no return values. 
The main use case is to remove long running tasks from the request/response cycle.

**Comment by jedie** [comment]
> The main use case is to remove long running tasks from the request/response cycle.

I realize that, of course :)
I didn't want to have the result in view either. I just thought that you could see it later in the admin.
It seems that you can only see in the admin that the task was executed or thrown an exception. But there is no way to save other information from the async task...

**Comment by philippeowagner** [comment]
The _result_ absolutely depends on what the background task does. 
This could be sending an email, updating an index or recomputing a hash.

**Comment by jedie** [comment]
I guess I said it badly.

i just mean the return value of the task function :)

Whereby one must then consider in which form one stores the task function: repr(), pickle, json ... or just accept strings?

**Comment by jedie** [comment]
btw.: In celery is the "result_serializer" settings: http://docs.celeryproject.org/en/latest/userguide/configuration.html#result-serializer and used json as default and has built-in support for JSON, pickle, YAML and msgpack: http://docs.celeryproject.org/en/latest/userguide/calling.html#calling-serializers

**Comment by philippeowagner** [comment]
If you need this feature you should go for celery. :)
