### ISSUE TITLE
Fail task without exception

### ISSUE THREAD

**Issue by poggenpower** [arteria/django-background-tasks#167]
Is there a way to fail a task without exception. 
Main goal is to fill the error field with an nice error description instead of a stack trace. 

I have same tasks where is pretty sure what the error is, but can't fix it programmatically, but if someone gets the right instructions it is easy for him/her for fixing it and wait that the task get rescheduled. 

For sure is is possible to create an own exception and put the instructions there, but it is still printed after the stacktrace and formatting is not nice

Thanks
  Thomas

**Comment by philippeowagner** [comment]
This specific use case has the be processed outside of BGT. 
Maybe you could catch one of the signals implemented in `background_task/signals.py`.
