### ISSUE TITLE
Object of type 'QuerySet' is not JSON serializable. Queryset not supporting in function call.

### ISSUE THREAD

**Issue by mukulmantosh** [arteria/django-background-tasks#171]
Background task does not work if we pass a queryset inside a method and gives back an error. 

```
user_detail = User.objects.get(id=1)

@background(schedule=datetime.now())
def notify_user(user_detail):
      pass

```
**Object of type 'QuerySet' is not JSON serializable.**

**Comment by philippeowagner** [comment]
This is how BGT is designed to work. 
Just pass the the ID and do the query inside `notify_user`. 

```
user_id = User.objects.get(id=1)

... 

@background(schedule=datetime.now())
def notify_user(user_id):
      user_detail = User.objects.get(id=user_id)
      ...

```

**Comment by mukulmantosh** [comment]
@philippeowagner Can you explain what's the reason behind BGT that we cannot pass the queryset ?

**Comment by philippeowagner** [comment]
The interface between the task process and the web process is the database. It's not possible to pass instances between two processes directly.

**Comment by mukulmantosh** [comment]
> The interface between the task process and the web process is the database. It's not possible to pass instances between two processes directly.

I have a doubt can you clear it out. BGT provides repeating tasks feature an alternative to cron. So my question is it more efficient to set a recurring task as a cron job or setup in BGT. 

For Example: 
Sending bulk notification to 100 users, Is it good to use BGT or Cron ? Which one would be better and why.

**Comment by philippeowagner** [comment]
We have serialised JSONs with thousands of IDs in it.
