### ISSUE TITLE
Logging Issue!!

### ISSUE THREAD

**Issue by sindhujit** [arteria/django-background-tasks#172]
I am trying to get logging results from django background tasks, and am unsuccessful. My requirement is to execute a background task when a django views.py calls it and have debugging on only for that tasks function. Also is there a way I can avoid "python manage.py progress_tasks" and run the tasks directly when the django views.py calls them?

**Comment by philippeowagner** [comment]
For the second part of your question:

Make a wrapper like this:
```

def add(a,b): 
  return a+b

@background
def add_later(a,b):
  return add(a, b)
```

**Comment by sindhujit** [comment]
I want django views to call background tasks and not the other way round.

**Comment by sindhujit** [comment]
I did read the docs. So I tried your above suggestion.
My views.py :
	data = {'user':str(request.user),'password':str(password)} 
	data1 = json.dumps(data)
	tasks.notify_user(data1,schedule=2)

@background(schedule=2)
def notify_user(data):
	return notify_user1(data)
	
def notify_user1(data):
	print('inside tasks wohoo',data)

But I never see the print statement show up in my django logs.

**Comment by sindhujit** [comment]
Any update on this?? @philippeowagner

**Comment by philippeowagner** [comment]
Try to write in a file directly or use the logger.

**Comment by sindhujit** [comment]
I have also tried that. It does not even go inside the function where the delay task is defined. Please help!!

**Comment by philippeowagner** [comment]
Please reopen if the error still persists.
