### ISSUE TITLE
Sending E-Mail Unit Testing 

### ISSUE THREAD

**Issue by mukulmantosh** [arteria/django-background-tasks#175]
I have written a function to send e-mail in Django. I have a written a unit test code in which i am over-riding the mail backend to in-memory ```django.core.mail.backends.locmem.EmailBackend```.

Not working when adding decorator:
```
@background(schedule=datetime.datetime.now())
def send_email_to_user(recipient_email, unique_code):
    subject, from_email, to = 'Welcome', settings.DEFAULT_FROM_EMAIL, recipient_email
    html_content = render_to_string('user/email/signup_link.html', {'code': unique_code})
    text_content = strip_tags(html_content)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
    return True
```
And without decorator working fine in unit test.

```
def send_email_to_user(recipient_email, unique_code):
    subject, from_email, to = 'Welcome', settings.DEFAULT_FROM_EMAIL, recipient_email
    html_content = render_to_string('user/email/signup_link.html', {'code': unique_code})
    text_content = strip_tags(html_content)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
    return True
```

**Comment by philippeowagner** [comment]
Please provide more info about "Not working".
Do you see an error? Is the task picked up? 
Do you have a 2nd process running for background tasks?

**Comment by mukulmantosh** [comment]
I am running unit test to check mail is getting received or not and definitely its not going to be send to a real SMTP Server instead of that i am sending mail to in-memory mail backend and i see that mail is not getting delivered and job is also not getting picked up.

**tests.py**
```
    def test_send_email(self):
        
        client = APIClient()
        mail.outbox = [] # Make mailbox empty.

        result = client.post('/api/v1/send-email/', {'email': 'test@test.com'})
        self.assertEquals(result.status_code, 200)
        self.assertDictEqual(result.json(), {"status": True, "message": "Mail Sent !"})

        
        print(mail.outbox) # [] -> Empty list. No mail received.     
        self.assertEqual(len(mail.outbox), 1)  # Check Mail received in outbox.
```

But when i remove the background decorator ```@background(schedule=datetime.datetime.now())``` then it works.

**Comment by philippeowagner** [comment]
The task must be executed by the runner. See https://django-background-tasks.readthedocs.io/en/latest/#running-tasks form more infos.

**Comment by mukulmantosh** [comment]
@philippeowagner already done its not working process_tasks not picking from test db.

**Comment by mukulmantosh** [comment]
@philippeowagner The Task runner is not executing from test database.
