### ISSUE TITLE
import problem with StringIO

### ISSUE THREAD

**Issue by JTiemi** [arteria/django-background-tasks#178]
I'm having this issue:
"....../lib/python3.6/background_task/models.py", line 8, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO' "

And I don't really understand, because there's no such line in the models.py on this Git. But I found out there is in the old package django-background-task. I think the command  "pip install django-backround-tasks" is installing the wrong package and I don't know how to fix it. Please help!

**Comment by anthony-jou** [comment]
You need to install 'django-background-tasks' instead of 'django-background-task'. That's the sublety.

**Comment by JTiemi** [comment]
That's the thing. I AM installing django-background-taskS.

**Comment by anthony-jou** [comment]
That’s really strange. Do you use PyCharm or something like this ?

**Comment by JTiemi** [comment]
Nope

**Comment by anthony-jou** [comment]
Can you tell me the version of your current package ?

**Comment by JTiemi** [comment]
In one of my tries I specifically installed the latest: "pip install django-background-tasks==1.2.0". Same issue. Pretty sure the other attempts also installed 1.2.0, if I recall correctly.

**Comment by anthony-jou** [comment]
When you installed the package, the package django-compat is also here ?

**Comment by JTiemi** [comment]
Not sure. Will check that out.

**Comment by philippeowagner** [comment]
@JTiemi make sure `django-background-task` is uninstalled as well.

**Comment by JTiemi** [comment]
@anthony-jou yes, the django-compat is there. And @philippeowagner, the django-background-task is not installed

**Comment by philippeowagner** [comment]
What compat/background-tasks version did you installed?

Could you try `from compat import StringIO` on the command line?

**Comment by philippeowagner** [comment]
Please reopen if your error still persists.
