### ISSUE TITLE
no such table: background_task_completedtask

### ISSUE THREAD

**Issue by alevchuk** [arteria/django-background-tasks#181]
i did `manage.py migrate`

```
  Applying background_task.0001_initial... OK
  Applying background_task.0002_auto_20170927_1109... OK
  Applying background_task.0003_auto_20190330_2147... OK
```

Yet when running `python manage.py process_tasks` I get table not found
```
django.db.utils.OperationalError: no such table: background_task_completedtask
```

versions
```
Django==2.1.7
django-background-tasks==1.2.0
```

**Comment by alevchuk** [comment]
./lib/python3.6/site-packages/background_task/migrations/0003_auto_20190330_2147.py contains
```
# Generated by Django 2.1.7 on 2019-03-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='creator_content_type',
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
```

**Comment by alevchuk** [comment]
I narrowed down the problem to `manage.py makemigrations` in Django 2.1.7

It creates a problematic migration:
```
manage.py makemigrations --dry-run
Migrations for 'background_task':
  .../lib/python3.6/site-packages/background_task/migrations/0003_auto_20190416_1619.py
    - Remove field creator_content_type from completedtask
    - Delete model CompletedTask
```
if I don't apply the `0003_auto_20190416_1619.py` migration then `manage.py process_tasks` works fine.

now, the question is, how to stop `makemigrations` from creating the faulty **0003_auto** migration?

**Comment by alevchuk** [comment]
same problem on django-background-tasks==1.2.4

**Comment by cnuss** [comment]
This went away once i added `django.contrib.admin` back to `INSTALLED_APPS`.

I think it's because `class CompletedTask` is included in https://github.com/arteria/django-background-tasks/blob/master/background_task/models_completed.py

**Comment by alevchuk** [comment]
https://github.com/arteria/django-background-tasks/commit/850d506c26948197779e63b530f4e9d39d17b0f1
