### ISSUE TITLE
scheduling doesn't work. without .now() function call doesn't wok.

### ISSUE THREAD

**Issue by ouzkagan** [arteria/django-background-tasks#183]
`from background_task import background

from django.contrib.auth.models import User

@background(schedule=10)
def notify_user():
    print('hello')`

i am calling it from views.py. but it doesn't work if i don't use .now after function. Also i don't get any errors.
 i added to settings.py also i did migrate. using django 2.2 python 3.7. 

i am trying to make task work daily not depends if someone open page or not.

**Comment by philippeowagner** [comment]
1. Do you see the `notify_user` task added to the queue under /admin/background_task/task/ ? 
2. Is the background task process running?

**Comment by ouzkagan** [comment]
Yes i see there but print doesn't work. i don't know what you mean by 2. question. how can icheck it?

**Comment by philippeowagner** [comment]
https://django-background-tasks.readthedocs.io/en/latest/#running-tasks

**Comment by ouzkagan** [comment]
yes. it works first if i run this command but eventually giving error

**Comment by ouzkagan** [comment]
as i notice now. when i tried before i didn't give any error :/

**Comment by ouzkagan** [comment]
after migration it stop giving error. now i will try call in view

**Comment by ouzkagan** [comment]
it still doesn't work after migration. errors stopped on this command 'python manage.py process_tasks'. But still doesn't printanything

**Comment by ouzkagan** [comment]
nope. it's not working :( :( :( :(
