### ISSUE TITLE
testing howtos

### ISSUE THREAD

**Issue by benzkji** [arteria/django-background-tasks#190]
I havent found a way to easily revert my tasks back to the .now version, when testing. As I see it, I would need to patch the tasks, but when and how? I strive for a one time solution, that reverts all @async methods transparently. For example with mock, or the like. Has anyone done something already?

**Comment by philippeowagner** [comment]
Nope.

**Comment by benzkji** [comment]
Ok. Thanks. Feel free to close. If I find something, I will dare a PR.
