### ISSUE TITLE
X (datetime, UUID), is not JSON serializable

### ISSUE THREAD

**Issue by oaosman84** [arteria/django-background-tasks#193]
Hey,
 This seems like a great tool, but when trying to use it I keep running into issues with serialization of (what should be, imo) serializable fields:
`Object of type datetime is not JSON serializable`
`Object of type UUID is not JSON serializable`

I think I could fix this pretty easily if I could specify the encoder being used (for instance, `DjangoJSONEncoder` can handle datetimes). Is there any way to specify a custom encoder, or can we add that functionality? (happy to add if maintainers are open to it)

(Of course, I can convert things to and from strings but will just add a lot of cruft... open to any other solutions people have in mind)

**Comment by philippeowagner** [comment]
Strings works great for us to be honest. It comes with a lot of positive side effects if the interface is low level.  

We could keep this open to see what others think about it.

**Comment by oaosman84** [comment]
Got it. So for something like a datetime, you would convert to string before calling the backgrounded function, then in the backgrounded function convert back to datetime?

Happy to wait and see what others think. Celery allows using different serializers (pickle, json, etc), but I do think allowing pickle is quite risky since it can allow arbitrary objects. I think allowing the caller to specify a custom encoder/decoder can be a good middle ground, allowing flexibility for simple types but making sure that the caller is explicitly aware of the types that are being serialized.

**Comment by philippeowagner** [comment]
I see lot more problems than benefit from passing serialised data here. 
Better pass the ID,hash,key,... to an object stored in the DB and fetch the latest data from the DB when using it.

**Comment by philippeowagner** [comment]
And note that we do want to be so simple as possible and we do not want not re-implement what Celery does.

**Comment by oaosman84** [comment]
Totally agree to keep things as simple as possible, but there are simple fields that could convert to/from strings (like datetime) that may not be stored in the DB (which is why Django itself has a DjangoJSONEncoder to cover those cases).

**Comment by philippeowagner** [comment]
No action from our side and no interaction in this issue. Closing it.
