### ISSUE TITLE
Reload process_tasks on code changes in dev mode

### ISSUE THREAD

**Issue by cedricfarinazzo** [arteria/django-background-tasks#195]
Hey!

It would be great to implement something that whatch code change and reload it if need as runserver do with his autoreloader.
As we only need this for developing, this mode can be enabled with a command line argument as `--dev`.

It's just an idea but it would be awesome.

Thanks you for this django package.

**Comment by philippeowagner** [comment]
Indeed, the idea is awesome. A PR is welcomed and will be merged if the solution is backward compatible.

You're welcome @cedricfarinazzo. Thanks for using django-background-tasks. 
https://github.com/arteria/django-background-tasks#donations ;)

**Comment by cedricfarinazzo** [comment]
OK, thanks.
I will try do to it.
I think I will use the same tools that ``runserver``: ``django.utils.autoreload``.

I will use ``autoreload.main`` for django < 2.2 and ``autoreload.run_with_reloader`` for django 2.2 or above to ensure backward compatibility,.

**Comment by philippeowagner** [comment]
@cedricfarinazzo awesome :) Will review your PR ASAP.
