### ISSUE TITLE
Best way to kill a task?

### ISSUE THREAD

**Issue by cory-weiner** [arteria/django-background-tasks#197]
Hi there I am using background-tasks to create a job that runs in perpetuity in the background.
However, I would like the user to be able to kill the process on command.

I have been able to accomplish this like so:
```

t = Task.object.all().first()
psutil.Process(int(t.locked_by)).kill()
t.delete()
```

This kills the process and deletes the task, however it ALSO stops the process_tasks que manager.

What is the best way to kill an actively running task without disrupting the que manager?

**Comment by philippeowagner** [comment]
There is no way to interrupt the running task.

**Comment by blkrt** [comment]
You just can kill tasks within dropping objects from database.

**Comment by shaklev** [comment]
Any updates on this ? Anyone has a solution on how to exit the tasks without actually killing the whole `python manage.py process_tasks` command ?
