### ISSUE TITLE
Django 1.7 and Python3 compatibility 

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#2]
@Luthaf 's https://github.com/lilspikey/django-background-task/pull/12 on the original repo (use with compat #1)

**Comment by Luthaf** [comment]
Do you have plans to host a stable fork here ? It would be easier to drop the 1.6 compatibility, as this version is deprecated by the Django team.

**Comment by philippeowagner** [comment]
Hi @Luthaf 
Yes, we will maintain and extend this fork of django-background-task.
 
We will provide support for two Django LTS versions (currently 1.4.x and 1.8.x) and what [officially is supported by Django](https://docs.djangoproject.com/en/1.8/internals/release-process/#supported-versions). This will be done using [django-compat](https://github.com/arteria/django-compat/). This works great in production (we are using both LTS versions and Django 1.7 at the moment in our projects.

What's already done:

* We cherry picked @weijia 's [completed task mechanism](https://github.com/weijia/django-background-task/commit/f9cc0f865c92a2f9405c20f4e78e46e6129c35f9) that logs what was done
* To avoid conflicts on PyPI/Github we renamed the repository to django-background-tasks (plural). For an easy upgrade from django-background-task to django-background-tasks, the internal module structure were left untouched.
* The latest version including completed task mechanism is on PyPI for production use. Currently Django 1.4 and 1.7. 

After integrating compat and updating the test we will review the PR you made and cherry pick what is still not covered.  

We would appreciate your help to improve [django-background-tasks](https://github.com/arteria/django-background-tasks).

**Comment by yannik-ammann** [comment]
@Luthaf your [pr](https://github.com/lilspikey/django-background-task/pull/12) has been merged into this repo.

**Comment by weijia** [comment]
Hi all,

I'm very happy that I contributed to the project. Could you please
help to *remove
the line:* __author__ = 'q19420' in models_completed.py? That's my internal
id in my company. And it was just added by the IDE automatically.

Regards,
Richard

2015-05-04 23:11 GMT+08:00 Yannik Ammann <notifications@github.com>:

**Comment by philippeowagner** [comment]
Sure @weijia
