### ISSUE TITLE
Expose "Last error" to other systems

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#20]
> mail_admin
> Opbeat
> Sentry

https://github.com/arteria/django-background-tasks/blob/master/background_task/tasks.py#L190

This could be done easily using Django's logging framework. See #16 as well.

**Comment by jvamvas** [comment]
@philippeowagner Until now, a task error was logged as a warning. In addition to the changes made in #16, I have raised the log level from `WARNING` to `ERROR`.

**Comment by philippeowagner** [comment]
Using the logging mechanism properly this issue is no longer applicable.
