### ISSUE TITLE
Best way to run task like a cronjob?

### ISSUE THREAD

**Issue by unformatt** [arteria/django-background-tasks#202]
I want a task to automatically be created when django starts and then run on repeat. I found how to make a task repeat but what is the best way to start that task when django starts? Doing it in AppConfig.ready to not ideal because this runs during unit tests, migrations, etc.

**Comment by emihir0** [comment]
I suggest having a look at https://github.com/Tivix/django-cron. It works very well. 

Although it would be nice to have both of these functionalities (cron-like-jobs and async-like-jobs) in a single app.

**Comment by philippeowagner** [comment]
You could have a look at https://django-background-tasks.readthedocs.io/en/latest/#repeating-tasks
