### ISSUE TITLE
No such table: background_task

### ISSUE THREAD

**Issue by the-moog** [arteria/django-background-tasks#204]
Related to pre-fork bug
https://github.com/lilspikey/django-background-task/issues/14

On adding the code in a new project it won't migrate or makemigrations

Turns out adding a static process in urls.py creates a chicken and egg synario.

It can't add the tasks because there is no database and it can't migrate because the task can't be created.

Simply commenting out the static (continuously running/run at start) tasks from urls.py breaks the deadlock.

Still a bug as I should not have to modify code to install the app.

**Comment by philippeowagner** [comment]
Could you check if it works with https://pypi.org/project/django-background-tasks/1.2.5/ please.

**Comment by philippeowagner** [comment]
Reopen if the error still persists. Tanks.

**Comment by Nimmerzeth** [comment]
@philippeowagner still persists on 1.2.5 installed with pip3

**Comment by ramihoudroge** [comment]
same issue here.

**Comment by ssyberg** [comment]
Also still seeing this issue

**Comment by Ericwonne** [comment]
Still having this issue.
Is it possible not to delete (even temporarily) my code to solve this?
