### ISSUE TITLE
No such table: backgorund_task when migrating with tasks.py with functions decorated with @background

### ISSUE THREAD

**Issue by CamilaAlvarez** [arteria/django-background-tasks#205]
If I try to migrate after implementing functions with this decorator the migration fails and gives a No such table: backgorund_task error.
I had to comment out all usages of the decorator to make the migration work

**Comment by Freyja-Folkvangr** [comment]
Did you tried `python manage.py migrate background_task` command?

**Comment by CamilaAlvarez** [comment]
Yes, and it gives me the same error 
`    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/calvarez/source/shopify-app/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/calvarez/source/shopify-app/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: background_task
`

**Comment by CamilaAlvarez** [comment]
It turns out that this happens only when you call functions decorated with background_task inside urls.py

**Comment by Friedjof** [comment]
It also took me a while. But then I implemented it like this

```python
try:
    update_machine_status(repeat=5, repeat_until=None)
except django.db.utils.OperationalError:
    print('Database not ready yet')
```
