### ISSUE TITLE
Disable retry when error

### ISSUE THREAD

**Issue by TwenTy47** [arteria/django-background-tasks#207]
Hi there. I noticed background_task automatically retries when there is an exception. **Is there any way to disable this retry?** 
I need to store to database after I fetch data from remote APIs. This automatic retry stores data from successful requests multiple times to database when one request fails and throws exceptions. I only implemented handlings for some kinds but not all exceptions (such as network error).

**Comment by philippeowagner** [comment]
Set `MAX_ATTEMPTS=1` in your settings. See https://django-background-tasks.readthedocs.io/en/latest/

**Comment by rjsnh1522** [comment]
Hi,
Actually MAX_TTEMPTS I have set as 1 but still, it is running twice.
I tried with zero also but it didn't work.

I want to run a thing in the background only once. doesn't matter it fails or passes.
so MAX_ATTEMPTS is not working for me.
