### ISSUE TITLE
Supporting Django 3.0 (django.utils.six -> six)

### ISSUE THREAD

**Issue by oaosman84** [arteria/django-background-tasks#209]
Hi,
  Django 3.0 [was released](https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/) today, and one of the breaking changes is:
* `django.utils.six - Remove usage of this vendored library or switch to six.`

Any plans to support this?

Looks like it could be as easy as just `from six import ...` instead of  `from django.utils.six import ...` (unless there are other breaking changes), so happy to do a PR if that's all there is.

**Comment by jaketothepast** [comment]
@oaosman84 we just hit this problem too, I'm happy to contribute as well if you are too busy, have to downgrade Django for now.

**Comment by oaosman84** [comment]
I have a PR out for this: https://github.com/arteria/django-background-tasks/pull/210, it's a pretty easy fix.

**Comment by philippeowagner** [comment]
This is fixed in upstream.
