### ISSUE TITLE
each task process (meaning "when i use same task with diffrent parameters did it create diffrent process or creates diffrent thread")

### ISSUE THREAD

**Issue by abdulrashid123** [arteria/django-background-tasks#215]

**Comment by abdulrashid123** [comment]
i am using each task multiple times i sit multiple process or multithreading

**Comment by philippeowagner** [comment]
Is this a duplicate of https://github.com/arteria/django-background-tasks/issues/200 ? 
Django version? Python version?

**Comment by abdulrashid123** [comment]
No

**Comment by philippeowagner** [comment]
Could you elaborate. Do not understand if it's a question or a problem.

**Comment by abdulrashid123** [comment]
when i use same task with diffrent parameters did it create diffrent process or creates diffrent thread

**Comment by philippeowagner** [comment]
Yes. You can run the task with multiple arguments.

eg 

send_email(to="me@foobar.com")
send_email(to="you@foobar.com")
