### ISSUE TITLE
Please update the current release version / update pypi 

### ISSUE THREAD

**Issue by schlaeps** [arteria/django-background-tasks#217]
The pypi version, the latest release version on GitHub, and the latest bundled version are all completely different, making this hard to install reliably. (The pypi release is almost a year old now and is incompatible with Django 3.0)

**Comment by tehfink** [comment]
Just ran into this as well: `pip install django-background-tasks` installed version 1.2.0, not 1.2.5.

**Comment by philippeowagner** [comment]
Thanks for your patience – will release ASAP!

**Comment by philippeowagner** [comment]
https://pypi.org/project/django-background-tasks/1.2.5/
