### ISSUE TITLE
Cannot run "python manage.py process_tasks"

### ISSUE THREAD

**Issue by imgeaslikok** [arteria/django-background-tasks#228]
I try to do a background task when the button is pressed in template. I've created a task and I've called it in a view. But the bg task does not work when the button is pressed however the task has been added to the background_task table in db. Also when I try to run "python manage.py process_tasks" command, i get an error such as below. 

Rescheduling data.task.model_create
Traceback (most recent call last):
  File "C:\Users\..\tasks.py", line 43, 
in bg_runner
    func(*args, **kwargs)
  File "C:\Users\..\tasks.py", line 24, in model_create  
    model_name = customer_name + str(model_names[i+1])
KeyError: 1
Marking task data.task.model_create as failed

**Comment by SirWindfield** [comment]
Got the same problem. Checking the `/admin` route shows that the task has been added but `process_tasks` doesn't execute them. It does however start, in contrary to the above.

**Comment by philippeowagner** [comment]
Nobody on our side uses Windows. Sorry.
