### ISSUE TITLE
Multiple tasks created instead of one

### ISSUE THREAD

**Issue by tonhal** [arteria/django-background-tasks#233]
Hi! I am calling a background function in `urls.py` to initiate the repeating task directly on startup.
```
refresh_tickets(repeat=300)
```
I have the background task in a `tasks.py` file.
```
@background(schedule=30)
def refresh_tickets():
...
```
However, if I run `python manage.py runserver` and `python manage.py process_tasks` what happens that there will be multiple tasks created. 2 on localhost (and 5 on our test server). First is created when I start the server, second is when I start the task processer. 

![Capture](https://user-images.githubusercontent.com/57263132/80576200-116c4800-8a05-11ea-822a-6f0094b55746.PNG)

Am I doing something wrong? Or should I use another way to start an indefinite task directly on startup?

**Comment by philippeowagner** [comment]
`urls.py` is not the place to call refresh_tickets I assume.

Setup the task one and repeat it. https://django-background-tasks.readthedocs.io/en/latest/#repeating-tasks

**Comment by tonhal** [comment]
It behaves the same in `apps.py`. When I start the server it creates one task, and then when I start the task processer it creates another one. Wherever I set it up, the setup will be duplicated. However, I managed to create a workaround (check if the object already exists).

**Comment by ianastewart** [comment]
I also start my repetitive tasks in urls.py - could not find anywhere better to initiate it.
But for each task I check if it exists and delete it before recreating it. Works fine.
