### ISSUE TITLE
tasks not running django 3.0

### ISSUE THREAD

**Issue by bizso09** [arteria/django-background-tasks#235]
I'm running django 3.0. The auto-discovery doesn't work and even manually scheduling tasks doesn't do anything. I can run tasks with manage.py process_tasks command only.

**Comment by bizso09** [comment]
turns out manage.py process_tasks has to run as a background process continuously, otherwise no tasks are ever run...

**Comment by apovall** [comment]
How did you get manage.py process_tasks to run as a background process continuously?

**Comment by philippeowagner** [comment]
https://github.com/arteria/django-background-tasks/issues/189#issuecomment-510808340 ??
