### ISSUE TITLE
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute     return Database.Cursor.execute(self, query, params) django.db.utils.OperationalError: no such table: background_task

### ISSUE THREAD

**Issue by bizso09** [arteria/django-background-tasks#236]
It is not possible to start django, because the tasks are trying to be loaded before the migration is applied. It's also not possible to do python manage.py migrate because of this error

**Comment by philippeowagner** [comment]
There are other sqlite related issues. Do not use this with sqlite.

**Comment by bizso09** [comment]
This is definitely not an sqlite issue. It happens with Postgresql as well. The issue is to do with loading tasks.py before the migration is applied, when django_background_tasks is first added. The workaround is to first do the migration before applying any code changes to the project.
