### ISSUE TITLE
Do I need to re-run process_tasks every time I make changes to my codes?

### ISSUE THREAD

**Issue by knguyen1794** [arteria/django-background-tasks#237]
Hey guys,

Let's say I have `process_tasks ` running in the background. Now I go into my project and add a new function with `background` decorator:

```
@background(schedule=8)
def dummy_task():
    bot().send_message("This is a message from tasks.")
```

And then I register it normally from command line, do I need to stop `process_tasks` and then rerun it?

It looks like I have to, because when I register the task, I can see that it's registered into database. But it's not run. The moment I rerun `process_tasks`, it sends out the message.

Is that so?

The reason of this question is that in my server, I run `process_tasks --duration 3600` which stop after 1 hour. Then we have a task scheduler to run this command every hour. It looks like whenever we make changes to the code, we'll have to wait till the next run for the new tasks to be executed?

***UPDATE: when I tried using `python manage.py process_tasks --dev` then this works. However it's not recommended to use in production, may I know why?

**Comment by knguyen1794** [comment]
Hi @philippeowagner ,

May I know if this project is still being maintained?

**Comment by philippeowagner** [comment]
We still use it in production, but we are all busy so open source development and community work falls a bit behind. 

Yes, you have to restart. It's like the runserver thingy...

**Comment by knguyen1794** [comment]
Thanks Philip!
