### ISSUE TITLE
get_query_set rollback

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#24]
get_query_set will be removed in the next version of django-compat
Re-handle this in the sources manually.

**Comment by iwaszko** [comment]
+1, I'm unable to run `process_tasks` on django 1.8. I'm getting: `AttributeError: 'TaskManager' object has no attribute 'get_query_set'`

**Comment by philippeowagner** [comment]
Thanks @iwaszko  for up-voting this issue. We are currently working on this is and an update will be released very soon! In the meantime you could use [django-compat 1.0.6](https://github.com/arteria/django-compat/releases/tag/v1.0.6) that still provides the monkey patched version of ``get_query_set``. This may be a BAD IDEA depending on what else you are running/have installed in your project.

**Comment by iwaszko** [comment]
Cool, I'm prototyping right now so it was easy to workaround, thanks for the quickest response though :)

**Comment by philippeowagner** [comment]
@iwaszko could you please give v [1.0.5](https://github.com/arteria/django-background-tasks/releases/tag/v1.0.5) a try and report any issues? It's on the PyPI. Thanks.

**Comment by iwaszko** [comment]
No exception this time. Thank a lot!
