### ISSUE TITLE
Hangs on python manage.py process_tasks

### ISSUE THREAD

**Issue by prdpspkt** [arteria/django-background-tasks#262]
I'm using it with django 3.1 and python 3.8. When I run python manage.py process_tasks hangs and returns nothing in console.

**Comment by sowdust** [comment]
this is happening to me as well recently, I still haven't understood why

**Comment by prdpspkt** [comment]
I changed the way code run replaced with cron jobs

**Comment by sowdust** [comment]
could you please elaborate a little more? so you are not using background_tasks anymore, or are you using it from cron jobs?

**Comment by prdpspkt** [comment]
Yes not using any more. It worked well in development machine but problem occurs after deployment in apache with passenger. I just created a python script and added to cron job. Because it was continuously running task for publishing scheduled posts.
