### ISSUE TITLE
How to schedule a Daily task and background task has no parameters

### ISSUE THREAD

**Issue by asifkhan69** [arteria/django-background-tasks#271]
I am using django-background-tasks in my project and it is running perfectly from last two years but now I have some new requirement to run a background task which I have created but facing some issues to configure and execute through django-background-task. 

@background(schedule=Task.DAILY)
def BatchProcessedReset():
    currdateobj = date.today()
    #todaydate = currdateobj.strftime("%Y-%m-%d")
    try:
        orgobj = Organisation.objects.filter(status=True)
        for org in orgobj:
            if org.batch_reset_date == currdateobj:
                org.batch_processed = 0
                org.batch_reset_date = datetime.now()+timedelta(days=365)
                org.save()
    except:
        pass
    return

this is the background task without any parameters and required to run daily once only. Second this task does not need to call from any django project it is isloated task that needs to run onec a day.
I tried to enter this task through Django admin when it execute it return below errors.

(msaaspro) Asifs-iMac4K:src asifkhan$ python manage.py process_tasks
Rescheduling BatchProcessedResting
Traceback (most recent call last):
  File "/Users/asifkhan/Development/msaaspro/lib/python3.6/site-packages/background_task/tasks.py", line 32, in bg_runner
    args, kwargs = task.params()
  File "/Users/asifkhan/Development/msaaspro/lib/python3.6/site-packages/background_task/models.py", line 214, in params
    args, kwargs = json.loads(self.task_params)
ValueError: not enough values to unpack (expected 2, got 0)
Marking task BatchProcessedResting as failed

seems that django-background-tasks can not configure without parameters.

anyone know, please advice how to handle this.

**Comment by asifkhan69** [comment]
Is there a way to set background task manually instead setting up from one of project apps or urls to create a background task.??

**Comment by asifkhan69** [comment]
I am closing this because I found out the way to add any background task in Task model manually for a background task with out calling from any project app or urls.py to set the background task to run. It is simple and we can set the frequency to daily or weekly what we want. thanks.

**Comment by HIMix** [comment]
> I am closing this because I found out the way to add any background task in Task model manually for a background task with out calling from any project app or urls.py to set the background task to run. It is simple and we can set the frequency to daily or weekly what we want. thanks.

I'm looking for such way. Could you please post here your way of doing it?
