### ISSUE TITLE
Async Background still runs tasks linearly instead of Parallel

### ISSUE THREAD

**Issue by pssolanki111** [arteria/django-background-tasks#275]
Hello there, Thanks for the excellent lib :)

I have an issue with the `BACKGROUND_TASK_RUN_ASYNC`.

I did a test with it set to false in the first go, which of course executed the tasks linearly.

I changed it to be True and it still executed the two tasks linearly one after another instead of doing it async.

Django version: `3.2.6` (latest)
python version: `3.8`
dj-vbg-tasks version: `1.2.5` (latest)

the task is a simple function which just print the argument passed to it.
both tasks are scheduled for almost the same time with a couple second's difference

Happy to provide more info if needed.

Any help is appreciated :)

**Comment by shaklev** [comment]
Any updates on this one ?

**Comment by pssolanki111** [comment]
hey @shaklev turns out it was actually running them async. Just that my tasks were not long enough to see the effect. 

Increasing the duration of tasks results in perfectly fine async execution.
