### ISSUE TITLE
Can't run migrations in Python 3

### ISSUE THREAD

**Issue by chadgh** [arteria/django-background-tasks#28]
This project seems to indicate support for Python 3. However, after installing into a Python 3 project, I'm not able to run the migrations successfully.

To reproduce:

1. Create virtualenv with Python3 (3.4 specifically) and pip install django 1.7.X and django-background-tasks (latest).
2. Create a Django project, add 'background_task' to the installed apps.
3. Run migrations

>  File ".../.virtualenvs/tmp-e3f3ffba6e5aedf/lib/python3.4/site-packages/background_task/admin.py", line 2, in <module>
>    from models_completed import CompletedTask
ImportError: No module named 'models_completed'

Am I doing something wrong, or is Python 3 not supported?

**Comment by chadgh** [comment]
See pull request #29 
It fixes the issue I'm seeing.

**Comment by philippeowagner** [comment]
I merged @chadgh's #29 Thanks for reporting and fixing this issue.
