### ISSUE TITLE
Tasks don't run in Python3

### ISSUE THREAD

**Issue by chadgh** [arteria/django-background-tasks#30]
Specifically I'm running a simple email task in python 3.4 and the task doesn't run. When I run the `process_tasks` management command it is just silent. This is even with `--log-level=DEBUG`.

The same tasks work fine with Python 2.7.

**Comment by philippeowagner** [comment]
Could you post your tasks.py please?

**Comment by philippeowagner** [comment]
Regarding the logging mechanism, please see #16.

**Comment by chadgh** [comment]
```
from background_task import background
from django.conf import settings
from django.core.mail import EmailMessage

from .search_indexes import full_index


@background
def reindex(config_slug, email_address):
    subject = '{} reindex complete.'.format(config_slug.title())
    msg = 'Reindex for {} finished successfully.'.format(config_slug)
    try:
        full_index(config_slug)
    except Exception as e:
        subject = '{} reindexing failed.'.format(config_slug.title())
        msg = 'There was an error while reindexing {}:\n{}'.format(config_slug, e.args)

    email = EmailMessage(subject, msg)
    email.to = [email_address]
    if settings.EMAIL_ADMINS_ON_REINDEX:
        email.bcc = list(settings.ADMINS)

    print('Sending email to {e}:\nSubject: {s}:\n{m}'.format(e=email_address, s=subject, m=msg))
    email.send()
```

This task works fine in Python2.

**Comment by philippeowagner** [comment]
Change the relative import (``.search_indexes``) to an absolute one and it will work.

**Comment by chadgh** [comment]
Made that change and it still isn't working.

The log says, `INFO:root:Running Task(myapp.tasks.reindex)` when I trigger the task, but the task in the database doesn't get the attempted count incremented and it doesn't move to completed tasks.

**Comment by philippeowagner** [comment]
Could you give it a try with an empty method to test if it's the background_task that has the Py3 issue or something different, eg something related to ``full_index``.

**Comment by chadgh** [comment]
I reduced the task to:
```
@background
def reindex(a, b):
    print('done')
```

This works in python 2 when running the `process_tasks` command. In python 3 it is silent. Num attempts isn't increased.

I'll create a django project from scratch in python 3 to see if I can reproduce in the simplest state.

**Comment by chadgh** [comment]
I'm not exactly sure what is going on but I did the following to reproduce and this time got an exception (in my actual project, it looks like it is just failing silently).

1. Created a new django project (called `core`) in its own virtualenv with Python 3.4 and Django 1.7.10.
2. Installed `django-background-tasks`.
3. Created a `tasks.py` file with the simple task:
```
@background
def test():
    print('done')
````
4. Imported and ran the `test` task from the django shell.
5. Ran `./manage.py process_tasks`

I get the following exception:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/background_task/management/commands/process_tasks.py", line 81, in handle
    if not tasks.run_next_task():
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/background_task/tasks.py", line 107, in run_next_task
    return self._runner.run_next_task(self)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/background_task/tasks.py", line 230, in run_next_task
    self.run_task(tasks, task)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/background_task/tasks.py", line 220, in run_task
    tasks.run_task(task.task_name, args, kwargs)
  File "/home/chadgh/.virtualenvs/tmp-3b687c658fb88a5/lib/python3.4/site-packages/background_task/tasks.py", line 100, in run_task
    proxy_task = self._tasks[task_name]
KeyError: 'core.tasks.test'
```

I also attempted this whole process by adding the task calling in a view and hitting the view in a running `runserver`, then running the `process_tasks` command. I got the exact same result.

**Comment by philippeowagner** [comment]
We will try to reproduce this. Did you have specified something in the ``settings.py`` and are you using the latest release? Thanks for the additional information @chadgh .

**Comment by chadgh** [comment]
`settings.py` wasn't changed except for the addition of `background_task` in the `INSTALLED_APPS` list.

I've reproduced this using the latest from PyPI (`django-background-tasks==1.0.5`).

**Comment by hnakamur** [comment]
I have the same issue and I created an example django project to reproduce this:
https://github.com/hnakamur/django-background-tasks-example
I attached results for Python 2 and Python 3 to the README at this page.

@philippeowagner Could you have a look at the example above? Thanks!

**Comment by philippeowagner** [comment]
We fixed the bug, could you @hnakamur @chadgh please give a try to django-background-tasks-1.0.7? It's on PyPI. Thanks.

**Comment by hnakamur** [comment]
@philippeowagner I tried django-background-tasks-1.0.7 with Python 3.4.3 and confirmed it works correctly.
https://github.com/hnakamur/django-background-tasks-example/commit/feac03e566023c679c204b4c42a464af60f179e8
Thanks for the quick fix!

**Comment by philippeowagner** [comment]
BTW @hnakamur you example project is awesome and could help noobies to set up django-background-tasks. It should be mentioned in the README. Is this in your interest as well (or will you drop it as it's fixed?)?

**Comment by hnakamur** [comment]
@philippeowagner It's my pleasure! Actually I am a newbie too and thought it is helpful if there is an example project using django-background-tasks.

**Comment by philippeowagner** [comment]
Great @hnakamur , I will mention it in the README.  :-)

**Comment by philippeowagner** [comment]
@chadgh feel free if you still perform any issues.

**Comment by chadgh** [comment]
Looks like it is working now. Thanks @philippeowagner @hnakamur for the fix!
