### ISSUE TITLE
Should tasks automatically be picked up?

### ISSUE THREAD

**Issue by grantmcconnaughey** [arteria/django-background-tasks#35]
My tasks are not automatically discovered and scheduled, they only work when I run the `./manage.py process_tasks` management command. Is this correct?

Here's what I have:

In my root urls.py file:

    from background_task import tasks
    tasks.autodiscover()

In one of my apps' `tasks.py` file:

    from background_task import background

    @background(schedule=5)
    def test_background_tasks():
        print('It worked!')

And in a view I am calling the `test_background_tasks` function.

I would expect 'It worked!' to be printed to my console within 5 seconds, but this does not happen. This only happens if I run the `./manage.py process_tasks` command. 

Are tasks not automatically picked up and scheduled when the project starts up? Do I have to run `process_tasks` command every time I want my scheduled tasks to be picked up? And if so, is there any way to put the `process_tasks` command in the background and not let it take up my console?

**Comment by philippeowagner** [comment]
We use [svc](http://cr.yp.to/daemontools/svc.html) and let the management run in the background. Basically the command [never exist](https://github.com/arteria/django-background-tasks/blob/master/background_task/management/commands/process_tasks.py#L80) and ``svc`` would just restart the process in case of a crash.

**Comment by grantmcconnaughey** [comment]
I'm not sure I understand. Do I have to run `process_tasks` for my tasks to run or not?

**Comment by philippeowagner** [comment]
Yes, ``process_tasks`` is the worker that process the tasks from the queue.

**Comment by gkeller2** [comment]
Hi, @philippeowagner .

I think the confusion comes from the installation instructions:

> (3.) Autodiscover tasks in your apps' tasks.py file. Add the following to your base urls.py so that autodiscover runs when your project starts up:
> 
> from background_task import tasks
> tasks.autodiscover()
> 
> Do this in case you are not using the management command to execute the tasks.

After reading these instructions, I understand that by adding that snippet of code to urls.py I don't need to invoke the management command `process_tasks` to get the tasks executed.

**Comment by greenafrican** [comment]
Yeah, agree with @gkeller2 . That is how I read the instructions. Having to manually run `process_tasks` to run the tasks seems counterintuitive to the intention of the package?

**Comment by jvamvas** [comment]
Thank you for pointing this out. I have removed step 3 from the installation instructions as it is highly ambiguous and not necessary for installation.
