### ISSUE TITLE
Can I use this package for production?

### ISSUE THREAD

**Issue by silviyaranirepo** [arteria/django-background-tasks#38]
If possible , could you guide me to use this in production environment? I tried to use celery periodic task to delete expired sessions. But celery production env setup is not easy way to do. So I planned to use django-background-tasks. Could you say the possiblities?

**Comment by philippeowagner** [comment]
@silviyaranirepo we use this in production in various projects. The main benefits of [django-background-tasks](https://github.com/arteria/django-background-tasks/) are the small footprint and its simplicity.

We use [daemontools](https://packages.debian.org/en/wheezy/daemontools) and then do a `exec setuidgid www-data python manage.py process_tasks` in the *run*-file to keep it up and running.

**Comment by keremgocen** [comment]
@philippeowagner are there any drawbacks to this approach in the long term, or have you by any chance discovered a better approach to this yet? I was wondering how this would behave as in "how often we will be spawning a process calling `manage.py`" and if it has any side-affect to the system?

**Comment by philippeowagner** [comment]
@keremgocen we are happy with this solution for years now. You start the background tasks process once and let it running beside the regular Django process. No drawbacks or side-affect to the system. He have servers where dozens of background tasks are running side by side.

**Comment by Faisal-Manzer** [comment]
@philippeowagner I am getting `-bash: exec: setuidgid: not found`
can you please guide.
