### ISSUE TITLE
Testings Tasks

### ISSUE THREAD

**Issue by gregpinero** [arteria/django-background-tasks#39]
How do you suggest I might write unit tests against the tasks I create?  And other code calling the tasks.

I'm thinking I'd need a way for all the tasks to  be run immediately and ignore the delay parameter during unit testing?

**Comment by jvamvas** [comment]
Here's an example:

```python
from django.test import TestCase

from background_task import background
from background_task.tasks import tasks


completed_tasks = []

@background()
def my_background_task(message):
    completed_tasks.append(message)


class MyBackgroundTaskTestCase(TestCase):
    def test_run_task(self):
        my_background_task(message="test")
        tasks.run_next_task()
        self.assertTrue("test" in completed_tasks)

```

The management command `process_tasks` might be a helpful reference: https://github.com/arteria/django-background-tasks/blob/master/background_task/management/commands/process_tasks.py#L85

**Comment by gregpinero** [comment]
Thanks.  That would work.  But let's say I have a function used all over the code like send_email.  And I decorate it to now be a background task.

Would I need to go into every single test and tell it to run_next_task().  Would there be a way to do this automatically everywhere?

**Comment by Zagrebelin** [comment]
You can use .task_function field of your task:

    @background
    def add(x,y):
        return x+y
    
    add(1,2)  # will create a task
    add.task_function(1,2)   # will launch your function immediatly and synchronously

also check out this (PR)[https://github.com/lilspikey/django-background-task/pull/17#issuecomment-163598417]. I accidentally pushed it to wrong repo.

**Comment by philippeowagner** [comment]
@Zagrebelin could you please send the [PR#17](https://github.com/lilspikey/django-background-task/pull/17#issuecomment-163598417) to this repo as well? Thanks
