### ISSUE TITLE
Add test cases for async task execution (WIP)

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#42]

**Comment by walterrenner** [comment]
First changes are made in 9370f4f6c313aa5e54162bc634f501c904ecc1ae

tox test passing but travis.yaml needs updates.

**Comment by walterrenner** [comment]
The current LTS version (1.8.*) is now also tested with the `BACKGROUND_TASK_RUN_ASYNC = True` setting.
