### ISSUE TITLE
Do background tasks have to go in tasks.py?

### ISSUE THREAD

**Issue by gregpinero** [arteria/django-background-tasks#44]
I have an existing function in utils.py that I'd like to turn into a background task.  Is that possible?

(I'm calling the function from all over the place so it wouldn't be feasible to replace it with one in tasks.py)

**Comment by walterrenner** [comment]
When i want an existing function to become a background tasks, i proceed as follows:

#### tasks.py

```
from background_task import background

@background(schedule=1)
def often_used_function_in_background(my_arg):
    # code from utils.py goes here
```

#### utils.py

```
from .tasks import often_used_function_in_background

def often_used_function(my_arg):
    # forwarding the arguments to the new background task
    often_used_function_in_background(my_arg)
```

**Comment by gregpinero** [comment]
Thanks.  That might work.

**Comment by JawnZ** [comment]
this really should not be closed. with commit 4cf5c0883780e54ab9efa4bb556b5d5fdec36a95 it seems to suggest that limiting things to tasks.py is "the wrong way" (and I agree). You're basically forcing code to be written in the tasks.py file when often it needs to be broke out (I have a few different scripts in my utils directory, but I shouldn't have to put all that code in a single tasks.py file)

**Comment by walterrenner** [comment]
@JawnZ Why not simply calling your utils scripts/functions from tasks.py?

A tasks.py file is just a very simple way to "autodiscover" what code to run in background.

**Comment by JawnZ** [comment]
@walterrenner that's actually what I ended up doing! Great suggestions. I misunderstood the earlier post and thought that they were saying the opposite:
Create the actual function in tasks.py and just create a dummy function in utils/scripts (Which seemed superfluous). 

I tried tweaking the auto-discover, but alas made it nowhere. The tasks.py being a pointer to my other functions works well though.
