### ISSUE TITLE
run_task_task not finding recently added tasks (until 5 seconds later)

### ISSUE THREAD

**Issue by gregpinero** [arteria/django-background-tasks#45]
I was trying the code recommended from issue 39 like this:

```
from django.test import TestCase

from background_task import background
from background_task.tasks import tasks

@background(schedule=5)
def my_background_task(message):
    send an email ...

class MyBackgroundTaskTestCase(TestCase):
    def test_run_task(self):
        my_background_task(...)
                    # time.sleep(5)  # See below
        tasks.run_next_task()
        print len(mail.outbox)
```

The problem is that tasks.run_next_task won't find the task until 5 seconds later.  I was under the impression run_next_task would be a way to run pending tasks immediately even if they're scheduled for the future.

Is there a different method that does that?  Would it make sense to add a method like that for unit testing?

**Comment by gregpinero** [comment]
I changed this issue a lot from what I originally wrote, so make sure to reread if you saw it on email first.

**Comment by jvamvas** [comment]
Yes you are right, @gregpinero. `run_next_task` does not run delayed tasks immediately. I too think such a method would be a useful feature.

**Comment by philippeowagner** [comment]
This is how BGT works "by design" at the moment. Closing this.
