### ISSUE TITLE
Ordering of keys matters in creation of task hash

### ISSUE THREAD

**Issue by drfraser** [arteria/django-background-tasks#47]
I was running into a situation where the task could not be found due to the hash value computed by
TaskManager.gettask() being different than that calculated by new_task(). I am using Python 2.7 UCS4 and Django 1.6.

The problem lies in lines 87 and 99 -

`task_params = json.dumps((args, kwargs))`

kwargs is not an OrderedDict, so how the keys are eventually arranged in the json string is not guaranteed.

I set the line to

`task_params = json.dumps((args, kwargs), sort_keys=True)`

and now things work as expected.

**Comment by walterrenner** [comment]
Hi @drfraser,

this sounds like an easy fix for this problem. Would you mind to send a PR and i will release your changes in the next version.

**Comment by drfraser** [comment]
as requested
