### ISSUE TITLE
Using named queues and multiple process instances

### ISSUE THREAD

**Issue by december1981** [arteria/django-background-tasks#49]
As a new feature, it would be nice if I could start a process instance of background task, with an argument only to pull certain tasks out of a named queue. The task decorator would have an optional queue parameter.

That would allow the user to architect their own multiprocessing if they wanted such a mode of asynchronicity. 

It would also allow more flexibility by having per-queue specific options. E.g. threading: having a per-queue setting for whether to run the tasks in that specific queue async or not (when the global BACKGROUND_TASK_RUN_ASYNC is not set).

**Comment by december1981** [comment]
fyi, I'm maintaining my own fork which supports named queues.

Here is the commit:

https://github.com/december1981/django-background-tasks/commit/cba825c40cbb14dc7a2c54f559c21513e30bd43b

**Comment by philippeowagner** [comment]
@december1981 are you interested to get your feature into [django-background-tasks](https://github.com/arteria/django-background-tasks/)?

**Comment by december1981** [comment]
@philippeowagner yes, I think it would be a useful feature to have. What do you think?

I have, by the way, now tested against the existing unit tests, and there are no problems - but I haven't added any additional tests for this new feature, as not sure about the best way to do this.

**Comment by jvamvas** [comment]
@december1981 I've just created two PRs to your fork, including a test case for named queues. Would you mind reviewing the requests and then perhaps opening a PR here?

**Comment by december1981** [comment]
@jvamvas Pull request is up (you'll note - I didn't properly fork from this repository, so I had to create a proper fork and push my branch task-queues to it)
