### ISSUE TITLE
Process restarts every hour

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-background-tasks#50]

**Comment by JawnZ** [comment]
I'm noticing something similar (I think).

I will have times where the ./manage.py process_tasks is still running but it doesn't execute anything until I restart it.

Is this the behavior you're seeing?

**Comment by philippeowagner** [comment]
Increase `MAX_RUN_TIME` will fix this...

**Comment by walterrenner** [comment]
I assume this is also fixed with the version 1.1.6. @philippeowagner can you confirm that?
