### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by chadgh** [arteria/django-background-tasks#51]
Any guess on when Django 1.9 might be supported?

**Comment by philippeowagner** [comment]
We at arteria mainly work with Django LTS 1.8.x so 1.9 is a bit out of scope for us at the moment, but of course django-background-tasks should work perfectly with Django 1.9 as well! 
What are the issues with Django 1.9 @chadgh ?  
As per design [django-compat](https://github.com/arteria/django-compat) should be upgraded first and than django-background-tasks whould use this new version wherever possible.

**Comment by chadgh** [comment]
I had assumed that it wouldn't work with 1.9 because the project says it only supports up to 1.8. I tried installing in a 1.9 project and when I ran the migrations nothing happened. I assumed again that it just wasn't working with 1.9. 

I, however, got it working after running `./manage.py migrate --run-syncdb`. This got the database tables created for background tasks and everything seems to be working just run.

This issue can probably be closed, but it might be helpful to know that you have to run the migrations with the `--run-syncdb` flag in order for background tasks to work in 1.9.
