### ISSUE TITLE
background_task table not created on makemigrations

### ISSUE THREAD

**Issue by matthewgo** [arteria/django-background-tasks#53]
Hi, I'm a newbie in Django and I need help in using this project.

I downloaded (using pip install) this project. Added 'background_task' to my INSTALLED_APPS,
I added the code in my tasks.py

from background_data import background

@background(schedule=1)
 def test_print():
    print("HEYY")

I am receiving an error that the word background after 'import' is underlined as red.
Also, when I call manage.py makemigrations, the supposed tables for background_data is not detected. Can you help me solve these issues?

**Comment by jvamvas** [comment]
@matthewgo, try to change the `import` line to:

```python
from background_task import background
```
`background_task` is the correct name of the package.

As for the migrations issue, try to call the `makemigrations` command explicitly for this app:
```
$ python manage.py makemigrations background_task
Migrations for 'background_task':
  0001_initial.py:
    - Create model CompletedTask
    - Create model Task
```
