### ISSUE TITLE
now process tasks with apache server

### ISSUE THREAD

**Issue by zhaochy1990** [arteria/django-background-tasks#55]
when i develop my site, I use `python manage.py runserver`. Everything works fine.

when I deploy my site, I use apache2.4.6 and mod_wsgi. I found the tasks are registered, but not processed at all. In Admin, `Home>Background_Task>Tasks` list all my tasks, but `Home>Background_Task>Completed tasks` shows no task was completed. I checked the log, and found the tasks were not been processed.

**Comment by philippeowagner** [comment]
Have you _something_ that keeps the background tasks _up and running_ according to the README (see https://github.com/arteria/django-background-tasks#running-tasks)?

**Comment by zhaochy1990** [comment]
yes, I followed the README.

I tried to solve this problem today, with `python manage.py process_tasks -v 3 --log-level=DEBUG`. what I discovered is when django-background-tasks query for the tasks from database, it found no task. But in fact, all the tasks are stored in database. 

I execute the query clause in my db console. the result shows all my tasks, this means the query is correct, but django-background-tasks find no task.

The following is the query clause:

```sql
QUERY = u'SELECT "background_task"."id", "background_task"."task_name", "background_task"."task_params", "background_task"."task_hash", "background_task"."priority", "background_task"."run_at", "background_task"."queue", "background_task"."attempts", "background_task"."failed_at", "background_task"."last_error", "background_task"."locked_by", "background_task"."locked_at" FROM "background_task" WHERE (("background_task"."locked_by" IS NULL OR "background_task"."locked_at" < %s) AND "background_task"."failed_at" IS NULL AND "background_task"."run_at" <= %s) ORDER BY "background_task"."priority" DESC, "background_task"."run_at" ASC' - PARAMS = (u'2016-07-11 14:37:59.072193', u'2016-07-11 15:37:59.072193'); args=(u'2016-07-11 14:37:59.072193', u'2016-07-11 15:37:59.072193')
```
after this query, it prints debug message
 ```
DEBUG:root:waiting for tasks
```
and then repeat this status again and again...

By the way, I'm using postgresql. Thank you very much.

**Comment by philippeowagner** [comment]
What happens if you call `python manage.py process_tasks ` in the production (virtual) env?
Basically 2 tasks must be running 

- 1 for processing requests and 
- 1 to process the tasks in the queue.

**Comment by zhaochy1990** [comment]
I'm not quite understand what you said "2 tasks", you mean 2 process?
What I said above is on my production env, the background tasks works fine with my develop env.

When i call `python manage.py process_tasks`, it shows nothing in the console.
And when i checking the running process, I only find one process running

**Comment by philippeowagner** [comment]
Yes, you're right – two processes, not two tasks.

**Comment by philippeowagner** [comment]
@zhaochy1990 could you manage to make it work? Please close the filed issue in this case or provide more information about your setup, settings, source, .. 
Thank you.

**Comment by pstragli** [comment]
Hi I'm running into the same issue stated by @zhaochy1990.
Tasks are being created correctly in the `background_tasks` table but when I run `python manage.py process_tasks` they are actually processed on dev environment only, while they are not processed in the production env (though by debugging, the generated SQL queries result in being correct).
I also see only one running process:
`1055     11152  0.0  0.1 287480 42952 pts/2    S+   09:19   0:02 python2.7 manage.py process_tasks`

@zhaochy1990 how did you solve the problem? Thanks in advance.

**Comment by zhaochy1990** [comment]
I use celery instead
