### ISSUE TITLE
Enhance to schedule job repeat regularly

### ISSUE THREAD

**Issue by 029xue** [arteria/django-background-tasks#58]
background current can only set a job to run at a specified time. 
`notify_user(user.id, schedule=timezone.now()) # at a specific time`

It's better if this can support repeat job run at a regularly time, e.g., run daily, weekly or at a specified time. e.g., 

`notify_user(user.id, schedule=timezone.now(), repeat=<daily/weekly/timedelta/etc.>)`

**Comment by JawnZ** [comment]
this can be done elsewhere/doesn't appear to be the intended function of this project.

http://stackoverflow.com/questions/573618/django-set-up-a-scheduled-job

**Comment by 029xue** [comment]
Thanks for the post, your recommendation is good for such scenario.

**Comment by philippeowagner** [comment]
I'd love to see the repetitive execution of jobs in this project. At the moment for example Celery may be a better solution for this problem but having such an easy setup is still tempting and because we use this app in many projects this may become true one day.

**Comment by jvamvas** [comment]
@029xue  We have included a simple implementation of this feature with 1.1.0rc1. You can find some documentation under https://github.com/arteria/django-background-tasks#repeating-tasks
