### ISSUE TITLE
v1.0.13 Django 1.10 setup.py error

### ISSUE THREAD

**Issue by 029xue** [arteria/django-background-tasks#60]
> Using cached django-background-tasks-1.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user1\AppData\Local\Temp\pip-build-1ixyhz2eon\django-background-tasks\setup.py", line 11, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1174: illegal multibyte sequence

I'm using Windows 10 Chinese version. Install in another pure English machine didn't encounter this.

**Comment by jvamvas** [comment]
Thank you for reporting this issue, @029xue. Could you please try and check whether it is resolved with version `1.0.14`?

**Comment by 029xue** [comment]
It's work well on 1.0.14. Thanks for the quick fix.
