### ISSUE TITLE
[Feature] Graphical Way to Show/manipulate Jobs in Queue

### ISSUE THREAD

**Issue by JawnZ** [arteria/django-background-tasks#61]
Hey all,

I want to be able to show users what jobs are sitting in the queue, and possibly let them manipulate them there ("delete" before a job is run for example)

Has anyone created a way to do this yet? I'm sure it wouldn't be that hard since everything is sitting in the database, but I don't know much about it.

Ideally it would involve some kind of AJAX. A button could push something into the queue on the page, the queue would update (without a page reload) and then you could "delete" jobs there (again, without a page reload).

If it doesn't exist I'll try my hand at it, but I have zero experience with AJAX, and it took me days to figure out django-background-tasks in the first place ;)

**Comment by philippeowagner** [comment]
Sorry for the late reply on this! 

This is a great idea. @arteria/devs worked on something similar for internal use.  We can definitely contribute something to this use case.

**Comment by JawnZ** [comment]
Hey @philippeowagner glad to hear you like the idea! It would be great if this got published into the project. I have a use-case for Django-background-tasks where the end user needs to see the "status" of the job. it would be AMAZING to show some kind of "percent" of a job, but that I think is way more difficult (vs. just showing if a job is waiting, running, or complete)

**Comment by JawnZ** [comment]
hello @philippeowagner I was wondering if there's any progress in moving your internal use code to the project?

**Comment by philippeowagner** [comment]
@JawnZ not really. The project name says it all … it's for background tasks.

**Comment by JawnZ** [comment]
Showing the status of tasks (Which you already have in the database) doesn't seem to violate the notion of background tasks.

**Comment by philippeowagner** [comment]
No, it doesn't at all @JawnZ . Just saying that we didn't worked on the other module for at least 1.5 years and let it go based on the lake of usage. On the other side we use django-background-tasks in almost every project. We implement tasks based on priority and let everything work in the background.

**Comment by JawnZ** [comment]
makes sense
