### ISSUE TITLE
Travis does not install correct Django version

### ISSUE THREAD

**Issue by jvamvas** [arteria/django-background-tasks#69]
Example:
Travis config: 1.8.* https://travis-ci.org/arteria/django-background-tasks/jobs/172598618/config
Actually installed: 1.10.3 https://travis-ci.org/arteria/django-background-tasks/jobs/172598618#L158

**Comment by walterrenner** [comment]
Fixed with 6603b8f0aae785fbc829473f7813818f277b6e6a
