### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by abusquets** [arteria/django-background-tasks#71]
Hi,
Is there any reason why the migrations are not in the module?

**Comment by chenyi1976** [comment]
googled half hour and get this, and it works.

"python manage.py makemigrations background_task needs to be ran first so that python manage.py migrate can create the table"

http://stackoverflow.com/questions/37898013/missing-db-table-for-django-background-tasks

**Comment by abusquets** [comment]
Of course, I know
