### ISSUE TITLE
Problems with repeat

### ISSUE THREAD

**Issue by the-doktor** [arteria/django-background-tasks#77]
Hi guys,

Tried to use repeating task functionality
Here goes what your README says:

  Repeating Tasks
  Repeating tasks can be initialized like this:
  notify_user(user.id, repeat=<number of seconds>, repeat_until=<datetime or None>)

Here goes my stuff:

the function to repeat itself:
  @background(schedule=20)
  def run_tracker(fake_param):
      devlog.info('TRACKER IS RUNNING')

initialised on startup as follows:
  run_tracker(None, repeat=30)

Here goes the error I'm getting when running python manage.py process_tasks
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/background_task/tasks.py", line 49, in bg_runner
     func(*args, **kwargs)
 TypeError: run_tracker() got an unexpected keyword argument 'repeat'

Here goes your decorator (found it in your source code). 
It does not have 'repeat' argument indeed.

def background(self, name=None, schedule=None, queue=None):
    '''
    decorator to turn a regular function into
    something that gets run asynchronously in
    the background, at a later time
    '''

Where am I wrong?

Thank you!
Eugene

**Comment by walterrenner** [comment]
Hi @the-doktor 

Thanks for reporting this Issue.

To Help you with you problem i first need to know which version you have installed. The "repeat" feature is still in beta and we hasn't been released it yet.

To use the beta you have to explicitly install the release candidate with `pip install django-backgorund-tasks==1.1.0rc3`. Otherwise the latest stable version will be installed.

Can you please double check that.

**Comment by the-doktor** [comment]
Hi @walterrenner

Thank you for the reply!

I used version 1.0.15
Tried to install release candidate as you suggested, got this

pip install django-backgorund-tasks==1.1.0rc3
Downloading/unpacking django-backgorund-tasks==1.1.0rc3
  Could not find any downloads that satisfy the requirement django-backgorund-tasks==1.1.0rc3
Cleaning up...
No distributions at all found for django-backgorund-tasks==1.1.0rc3

**Comment by philippeowagner** [comment]
@the-doktor beside having a typo in your call (`django-backgorund-tasks==1.1.0rc3`) version `1.1.0rc2` is the latest RC published. There is a race condition in the RC version of this module in case you are using multiple thread. I suggest to wait for the next stable version coming in the next days. 

* #79

**Comment by DanSantoDomingo** [comment]
Im getting the same error, i'm running version 1.2.5
