### ISSUE TITLE
unexpected keyword argument 'repeat'

### ISSUE THREAD

**Issue by jsartre** [arteria/django-background-tasks#83]
Hi,
I am trying to implement a repeat background task through the following function but I get the this error (in the admin):
`
Traceback (most recent call last):
  File "/Users/josephsartre/Documents/Sites/rise/venv/lib/python2.7/site-packages/background_task/tasks.py", line 49, in bg_runner
    func(*args, **kwargs)
TypeError: test_task() got an unexpected keyword argument 'repeat'
`

Any of you guys had that in the past?
Thanks!
J.
my code so far:
tasks.py:
`
@background(schedule=60)
def test_task(message="Run test scraper"):
results = scraper()
update = update_source_date(results[5])
logger.debug('demo_task. message={0}'.format(message))
`

views.py:
`def run_scraper(request):
results = test_task(repeat=120, repeat_until=str(datetime.datetime.now() + datetime.timedelta(minutes = 30)))
return render(request, 'scraper/scraper.html', {'results': results})`

**Comment by jsartre** [comment]
Resolved on my end. For those having similar issues:
-> Need to install RC2 version of code
`pip install django-background-tasks==1.1.0rc2 --upgrade`
-> **WARNING**: It requires django 1.10.6

J.

**Comment by philippeowagner** [comment]
@arteria/devs django 1.10.6 ?
