### ISSUE TITLE
Latest version 1.1.x is not available through pip

### ISSUE THREAD

**Issue by soulhunter1987** [arteria/django-background-tasks#88]
The latest version available is 1.1.0rc

**Comment by walterrenner** [comment]
Thanks @soulhunter1987 for reporting this. This is still an open task. We will publish the latest version on PyPi in the next days. Thanks for your patience.

**Comment by philippeowagner** [comment]
https://pypi.python.org/pypi/django-background-tasks/1.1.6

**Comment by grote** [comment]
The 1.1.8 release seems to have a bug that is solved by the 1.1.9 release, but only the broken 1.1.8 is available via pip while the 1.1.9 fix is not.
