### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by albertogargar** [arteria/django-background-tasks#91]
I still having this issue https://github.com/arteria/django-background-tasks/issues/71

Is there any reason why the migrations folder are not in the module? I know I can get it running makemigrations, but I still having problems with Heroku, because they run "manage.py migrate" and read from the collected packages. 

Same problem here: http://stackoverflow.com/questions/42595223/django-background-tasks-migrations-on-heroku

Thanks! :-)

**Comment by philippeowagner** [comment]
Thanks for reporting it again. We will add the migrations ASAP.

**Comment by philippeowagner** [comment]
Thanks for reporting it again. We will add the migrations ASAP.

**Comment by walterrenner** [comment]
Migrations were added in the latest version.
Please install v1.1.9 from the PyPI 📦
https://pypi.python.org/pypi/django-background-tasks/1.1.9
