### ISSUE TITLE
should I run process_tasks as a parallel process in order to execute tasks?

### ISSUE THREAD

**Issue by chapkovski** [arteria/django-background-tasks#98]
I run a project in Django 1.8.8. 
The scheduled work is not executed though unless I start a separate process "python manage.py process_tasks". Then everything works fine. Sorry for my ignorance, but is it intended to be so or something wrong with my code?

**Comment by walterrenner** [comment]
Hi @chapkovski,
your code seems absolutely fine. Tasks are not executed in same process as your django application.
Here is the relevant part of the documentation: http://django-background-tasks.readthedocs.io/en/latest/#running-tasks
